version: '3.9'

services:
  couchbase-init:
    container_name: couchbase-init
    hostname: couchbase-init
    build:
      context: ./couchbase
      args:
        VERSION: "6.6.3"
    environment:
      USERNAME: "admin"
      PASSWORD: "admin1"
      NODE_TYPE: "init"
    ports:
      - "8091:8091"
  couchbase:
    deploy:
      replicas: 0
    build:
      context: ./couchbase
      args:
        VERSION: "6.6.3"
    environment:
      USERNAME: "admin"
      PASSWORD: "admin1"
      NODE_TYPE: "join"
      NODE_JOIN: "couchbase-init"
  ldap:
    container_name: ldap
    hostname: ldap
    build:
      context: ./ldap
      args:
        DOMAIN: "seems.cloud"
        PASSWORD: "admin123"